<?xml version="1.0"?>
<package format="3">
  <name>radarays_gazebo_plugins</name>
  <version>0.0.0</version>
  <description>ROS 2 / Gazebo Harmonic migration package for radarays_gazebo_plugins.</description>

  <maintainer email="amock@uos.de">Alexander Mock</maintainer>
  <license>TODO</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>ament_index_python</depend>
  <depend>launch</depend>
  <depend>launch_ros</depend>
  <depend>rclcpp</depend>
  <depend>rclpy</depend>
  <depend>ros_gz_sim</depend>
  <depend>rmagine_gazebo_plugins</depend>
  <depend>radarays_ros</depend>
  <depend>rmagine</depend>
  <depend>sensor_msgs</depend>
  <depend>gz-sim8</depend>
  <depend>gz-plugin2</depend>
  <depend>gz-transport13</depend>
  <depend>gz-common5</depend>
  <depend>gz-math7</depend>
  <depend>gz-msgs10</depend>
  <depend>gz-rendering8</depend>
  <test_depend>ament_cmake_test</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
